### ISSUE TITLE
Testfile cifar10-test-data-class3.npz can't be loaded via pk.resource_filename() instruction in cnv_end2end_example.ipynb notebook

### ISSUE THREAD

**Issue by chhait07** [Xilinx/finn#271]
Hi,
on executing line `fn = pk.resource_filename("finn", "data/cifar10/cifar10-test-data-class3.npz")` in the `cnv_end2end_example.ipynb` notebook i receive the error message `No such file or directory`. See screenshot.

![Issue_Cifar](https://user-images.githubusercontent.com/78212618/106353541-a7623580-62eb-11eb-8273-15314a7ebd55.png)

I suppose the path should point to this file: https://github.com/Xilinx/finn/blob/master/src/finn/qnn-data/cifar10/cifar10-test-data-class3.npz . So, how do I have to change the instruction so that it works? I tried some stuff but nothing worked.

**Comment by maltanar** [comment]
Hi, thanks for reporting this! Looks like a number of resource paths in notebooks weren't updated in v0.5, I just pushed a fix for this:

https://github.com/Xilinx/finn/commit/c69f4d30c03c24d844b33e6c4081f7db8f64a940

Essentially `pk.resource_filename("finn", "data/cifar10/cifar10-test-data-class3.npz")` needs to change to `pk.resource_filename("finn.data", "cifar10/cifar10-test-data-class3.npz")` for this case. The commit also includes a fix for #269 -- can you verify that this works for you as well?

**Comment by chhait07** [comment]
Hi, 
I changed the line as you described above. Unfortunately it's still not working, see the following screenshot. The error says:
*FileNotFoundError: [Errno 2] No such file or directory: '/workspace/finn-base/src/finn/data/cifar10/cifar10-test-data-class3.npz'*

![Error](https://user-images.githubusercontent.com/78212618/107011508-061a2a00-6798-11eb-8028-c055da45f831.png)

**Comment by chhait07** [comment]
Hi,
I switched to branch c69f4d3 and tried again. This fixed it for me.
